### ISSUE TITLE
Bewerbungsformular - Loading Animation

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#101]
Als User möchte ich, sehen wenn die Daten im Bewerbungsformular verarbeitet werden und ich ggf. warten muss, bis eine Antwort zurück kommt.

**Acceptance criteria:**
- Der Button bekommt eine unabhängigen Ladezustand
- Das Modal bekommt einen unabhängigen Ladezustand

**References:**
https://dribbble.com/shots/16496437-Loading-button-animation

**Comment by Listor** [comment]
Die Lade-Animation ist jetzt auf DEV testbar https://chartreuse-sky.cloudvent.net/de/jobs/#junior-strategic-account-manager-1327578



https://github.com/c4a8-web/shared-components/assets/4637866/ce97160d-bb8f-46c3-8417-fa402a0d2180

**Comment by KristinRolfes** [comment]
Ist super geworden @Listor

**Comment by Listor** [comment]
Ist auf STAGING
