### ISSUE TITLE
Form Attachments kann mit mehreren Dateien umgehen

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#102]
Als User möchte ich mehr als ein Dokument in das Bewerbungsformular hochladen können.

**Acceptance criteria:**
- Die Form Attachments [Komponente](https://c4a8-web.github.io/shared-components/?path=/story/components-form-attachments--not-required) kann mit mehreren Dokumenten umgehen
- Man muss zwingend ein Maximum an hochladbaren Dateien spezifizieren (Default: 3)

**Design:**
<img width="450" alt="image" src="https://github.com/c4a8-web/shared-components/assets/4637866/02e77aa9-b3a5-48c6-b74b-d9e89a03a419">

**Infos:**
Die Dateinamen sollen untereinander in der Komponente aufgelistet werden. Herausfinden, wie groß die Uploadgröße bei Personio ist und die Texte entsprechend anpassen. Auch prüfen, ob die Größe pro Datei oder Pro Bewerbung zählt und ggf. die Logik im Frontend anpassen.

**Comment by Listor** [comment]
Ist jetzt auf DEV https://chartreuse-sky.cloudvent.net/de/jobs/#trainee-microsoft-modern-workplace-1350465 muss noch mit Kerstin abstimmen, ob die Bewerbungen wirklich korrekt ankommen.

**Comment by Listor** [comment]
Funktioniert und kann auf DEV getestet werden @cakageka

**Comment by cakageka** [comment]
@KristinRolfes Meiner Meinung nach ist der aktuelle Ablauf nicht intuitiv genug.

Folgendes funktioniert gut:
- Das Hochladen mehrerer Dateien gleichzeitig mittels Drag & Drop
- Das Hochladen mehrerer Dateien gleichzeitig über den Dateiupload

Jedoch gibt es ein Problem:
Wenn ich eine Datei hochlade und anschließend über das "+"-Symbol eine weitere hinzufügen möchte, wird die erste Datei ersetzt, selbst wenn die zweite Datei einen anderen Dateinamen hat. Dieses Problem tritt auf, wenn die Dateien in unterschiedlichen Ordnern gespeichert sind. Um erfolgreich mehrere Dateien hochzuladen, müssen sie alle im selben Ordner liegen. Wenn dies nicht anders zu lösen ist, sollten wir einen entsprechenden Hinweis für die Benutzer:innen hinzufügen, um Missverständnisse zu vermeiden.

**Comment by Listor** [comment]
So umsetzen:

<img width="761" alt="Bild (1)" src="https://github.com/c4a8-web/shared-components/assets/4637866/5d9eeda1-20da-4876-ad34-881a074c57e0">

**Comment by Listor** [comment]
Die neue Implementierung ist jetzt auf DEV zu sehen https://chartreuse-sky.cloudvent.net/de/jobs/#cyber-security-architect-1335399

**Comment by cakageka** [comment]
Wir sprechen unsere Bewerber in der Du-Form an, daher bitte die Fehlermeldung korrigieren:
DE Bitte wähle ein gültiges Dateiformat und achte darauf, dass der Dateiname keine Sonderzeichen enthält.
EN Please choose a valid file format and make sure that the file name does not contain any special characters.

Ansonsten finde ich es super. Fühlt sich gut an.

**Comment by Listor** [comment]
Alles klar, habe die Texte angepasst. Habe dabei auch Spanisch noch übersetzt, kann ich aber inhaltlich nicht beurteilen.

ES: "Elija un formato de archivo válido y asegúrese de que el nombre del archivo no contiene caracteres especiales."

Ist jetzt auf STAGING
