### ISSUE TITLE
Fehlermeldungen im Bewerbungsformular

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#103]
Als User möchte ich auf Fehler beim Versenden meiner Bewerbung hingewiesen weredn.

**Acceptance criteria:**
- Es gibt inline Fehlermeldungen, die feldbezogene Fehler ausgeben
- Es gibt [allgemeine Fehlermeldungen](https://c4a8-web.github.io/shared-components/?path=/story/components-modal-error--modal-error), die wie die Bestätigungs-Meldung, einen eigenen Screen bekommen
- Das Erdmännchen Icon wird in der allgemeinen Fehlermeldung angezeigt
- Eine Liste mit den möglichen Fehlermeldungen, die in die Übersetzung mit aufgenommen werden müssen

**Infos:**
Herausfinden, welche Fehlermeldungen von der Schnittstelle kommen und bestimmen in welchem Fall, welche Fehlermeldung ausgeben werden soll.

**Comment by Listor** [comment]
Fehlermeldungen beim Dokumenten-Upload:

- Unauthorized 401
- Forbidden 403
- Playload too large 413
- Unprocessable Entity 422
- Too many requests 429
- Internal Server Error 500

Fehlermeldungen beim Absenden der Bewerbung:

- Bad Request 400
- Unauthorized 401
- Forbidden 403
- Too many requests 429
- Internal Server Error 500

Ich würde die Fehlermeldungen 400, 401, 403, 422, 429 und 500 alle mit einem generischen Fehler ausspielen. Der User hat hier nicht wirklich Einfluss darauf, ob der Request abgesendet werden kann. Dies kann auf Fehler in unserer Implementierung oder bei Personio hindeuten. Auch Too Many Requests, können wir dem User nicht sagen, wann er wieder einen Request abschicken darf.

![Image](https://github.com/c4a8-web/shared-components/assets/4637866/d45f1842-3e5f-4c48-a402-6803cb6db74c)

Dafür dann das generische Erdmännchen, anstatt der Rakete wie hier https://c4a8-web.github.io/shared-components/?path=/story/components-modal-error--modal-error . Der User kann hier Nichts mehr machen, aus meiner Perspektive.

Fehlermeldungen für Felder, gibt die Schnittstelle nicht raus laus Dokumentation, also gibt es auch Nichts, das wir dann behandeln können.

Bei 413 könnten wir dem User mitteilen, dass seine Datei zu groß ist, obwohl unser Frontend darauf prüft, gibt das keine 100%ige Sicherheit. Kann also sein, dass der Server das Trotzdem ausgibt.

Mein Vorschlag wäre hier dann den Fehler am Feld anzuzeigen mit der Meldung. "Eine oder mehrere Dateien sind zu groß.". Das ist auch der Frontend Validierungstext, der im Moment angezeigt wird und schon in der Übersetzung drin ist.

**Comment by Listor** [comment]
@cakageka @KristinRolfes

**Comment by KristinRolfes** [comment]
**Wie gerade besprochen:** 
- wenn für den Nutzer die Möglichkeit besteht konkret etwas zu ändern (wie Datei zu groß) sollten wir das ausspielen.
- ansonsten wie schon von dir vorgeschlagen: Erdmännchen Fehlermeldung inkl. Mail und Telefonnumer zur Kontaktaufnahme

**Comment by Listor** [comment]
So würde die generische Fehlermeldung dann aussehen @KristinRolfes 

![Image](https://github.com/c4a8-web/shared-components/assets/4637866/2136937b-ccb2-4cd4-9a55-088556a91579)

**Comment by KristinRolfes** [comment]
@Listor, fnde ich gut!

**Comment by cakageka** [comment]
Da würde man sich doch wünschen, dass die Fehlermeldung öfter kommt :-)

**Comment by Listor** [comment]
Ja ist nur Platzhalter, aber ich nehm den Text mit in die Änderungen.

**Comment by Listor** [comment]
Die generische Fehlermeldung kann man jetzt hier testen https://c4a8-web.github.io/shared-components/?path=/story/components-job-detail--error-generic 

Die Fehlermeldung mit der Dateigröße kann man leider nicht in den Shared-Components statisch testen, nur mit einem echten laufendem Storybook, dass quasi für manche Fälle einen "Server" simuliert.

Die Fehlermeldung sieht so aus, wie wenn man selber eine zu große Datei hochlädt, nur diesmal kommt die Antwort vom Server. Den Testfall kann ich auch nicht im Live System herstellen, weil ich die Schnittstelle von Personio nicht dazu zwingen kann, mir dieses Ergebnis zu liefern.

Macht das Feature relativ schwer bis unmöglich zu testen :/

Hier sieht man das Frontend schlägt bei 35.1KB nicht fehl, schickt also den Request an mein Fake Backend, das sagt dann aber, die Datei ist doch zu groß, und man landet dann hier und könnte ggf. seine Datei noch leicht verkleinern. Der Fehler sollte generell kaum auftreten, könnte mir nur vorstellen, dass die Komma Zahlen unterm Strich, die wir im Frontend errechnen, nicht 100% mit dem vom Backend übereinstimmen und dadurch so ein Fehler auftreten könnte.

![Image](https://github.com/c4a8-web/shared-components/assets/4637866/da261c1f-0467-48ee-a30d-bfe1e60a8403)

@cakageka ist die Frage, ob dir das als "Test" reicht oder ob wir Zeit investieren wollen, diesen Fall testbar zu machen?
