### ISSUE TITLE
Tab-List Swipebar

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#112]
Sobald kein Platz mehr ist um den Inhalt darzustellen, sollte der Inhalt swipebar sein und man so die nicht zu sehenden Tabs anzeigen. 

Wie das visuell aussieht, nochmal mit Kristin besprechen, sobald am Ticket gearbeitet wird.

*Development:* https://c4a8-web.github.io/shared-components/?path=/story/components-tab-list--tab-list

**Comment by Listor** [comment]
Kann auf STAGING getestet werden https://fluffy-soap.cloudvent.net/en/security/excellence-awards-2024/

**Comment by cakageka** [comment]
Bereits live
