### ISSUE TITLE
Logo List mit optionalem Aspect Ratio

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#121]
Wir möchten die Möglichkeit haben, als Parameter einen Aspect Ratio übergeben zu können.

Dieser soll optional an die Bilder übergeben werden, so dass man ein einheitliches Verhältnis der Flächen erzielt.

**Comment by JHPNE** [comment]
Die Komponente besitzt nun einen Parameter über welches man die Aspect Ratio steuern kann. Hier einsehbar für die "CSOC Customer Wins 2023": https://fluffy-soap.cloudvent.net/en/security/excellence-awards-2024/
