### ISSUE TITLE
Seo Anpassungen von Radius auf Produkte ausrollen

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#122]
Wir haben in diesem [Commit](https://github.com/c4a8-web/www-radius-as-a-service-com/commit/ab596e3327887248d79e9e4da8a8624111f46fe4) einige Seo relevante Änderungen ausgerollt.

Diese sollen auch auf die anderen Produkte ausgerollt werden.

Also explizit soll der BLOG auch aus den Produkten entfernt werden, so wie bei Radius, zumindest aus der Sichtbarkeit.

Der Paramater "shared_bundle" soll aber NICHT in der config gesetzt werden.

Die Änderungen müssen in den Produkten einzeln umgesetzt werden

- [x] SCEPman
- [x] Konnekt
- [x] RealmJoin
- [x] realmigrator
- [x] RealMigrator
- [x] Unified Contacts

In der Developer Console wird eine Info ausgegeben, wenn gebundelt wird.

<img width="942" alt="image" src="https://github.com/c4a8-web/shared-components/assets/4637866/433ff88b-06ed-47d5-9984-bbd54ebefddd">

Der Bundle wird nur in STAGING / PRODUCTION ausgeführt. Die Info sollte dementsprechend nicht in der Console auftauchen.

**Comment by JHPNE** [comment]
Die Änderungen befinden sich auf den Produktseiten im Staging.
