### ISSUE TITLE
Animations im Hero & anderen Komponenten

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#141]
Ich glaube wir haben hierfür kein Ticket angelegt.

Wir wollen ja die Lottie Animation aus After Effects an möglichst vielen Stellen einsetzen können. Deshalb hier das Ticket dazu.

**Comment by Listor** [comment]
Komponenten in denen die Lottie Animation jetzt funktioniert:

- Hero
- Text-Image

Wo es etwas komplexer ist und deshalb erstmal nicht eingebaut wurde:

- Accordion ( Hier ist es relativ kompliziert die Lottie Animation einzubauen, weil wir mit dem Aufklappen des Accordions, die Bilder austauschen, Fallback Bilder haben, die Mobil oder Desktop unterschiedlich eingeblendet werden. Hier müsste man deutlich mehr Zeit investieren, um es dort zu integrieren. )

**Comment by Listor** [comment]
Das Beispiel im Hero kann man jetzt hier sehen, der Rest ist dann in Storybook, sobald es auf Master ist.

https://chartreuse-sky.cloudvent.net/de/modern-workplace/microsoft-365-copilot

**Comment by cakageka** [comment]
Sehr cool. @lenadaflis Hättest du die Copilot Animation für mich? Dann würde ich die Seite jetzt überarbeiten.

**Comment by lenadaflis** [comment]
@cakageka 
https://c4a8.sharepoint.com/sites/GKGABMarketing/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FGKGABMarketing%2FShared%20Documents%2FGeneral%2FCorp%2FDigital%2FMotion%2FAnimation%2Fgk%2DCopilot%2DAnimations%2F%5FLandingpage&viewid=e6e8b4ca%2D5905%2D484a%2D99da%2Dfd602106a839

**Comment by cakageka** [comment]
s. #264

**Comment by Listor** [comment]
@cakageka der Feature Request muss noch gemerged werden. Ich nehme an, dass dies dann jetzt gemacht werden soll?

**Comment by cakageka** [comment]
Ja, bitte. Dachte, dass hätten wir schon so besprochen.

**Comment by Listor** [comment]
Ist jetzt auch gemerged.
