### ISSUE TITLE
Storybook Addon um SVG Animationen zu speichern

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#151]
Das Addon HTML Download, um die animierten Shapes aus Storybook als SVG herunterzuladen, muss auf die neuste Storybook Version geupdated werden. 

Beispiel-Animation: https://c4a8-web.github.io/shared-components/?path=/story/components-shape--shape-fast-forward

Aktuell ist es nicht mehr funktional und wird auch nicht geladen.

**Comment by cakageka** [comment]
@Listor Das kannst du nachrangig behandeln. Wenn wir jetzt in der Lage sind, Lottie-Animationen auszuspielen, werden wir diese Funktion ggfs. nicht mehr benötigen.
