### ISSUE TITLE
Hero Refactoring // Konsolidierung

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#154]
Um die Anforderungen an die Hero Komponente zu besprechen, hier ein Ticket mit meiner Analyse, als Diskussionsgrundlage.

![Hero Requirements](https://github.com/c4a8-web/shared-components/assets/4637866/1f0ee9dc-1e9d-4a19-b625-96b9881b8038)

**Comment by Listor** [comment]
- Logo Leiste
- https://www.radius-as-a-service.com/partner/ die 2 Tabs unten

**Comment by Listor** [comment]
### Akzeptanzkriterien:

1.  Konfiguration:
- Standardmäßig nimmt die Komponente den Raum des Inhalts ein und zentriert diesen vertikal.
- Der Hintergrund kann farbig, als Bild, SVG oder Lottie-Animation gestaltet sein, wobei die Breite prozentual einstellbar ist.
- Optional kann eine Animation über beide Spalten hinweg eingefügt werden (Text-Icon-Animation wie auf Karriereseite)
2.  Layout:
- Die Komponente besteht aus zwei Spalten (Standard: 8 Einheiten für Text, 4 für Bilder/Animationen), deren Breite anpassbar ist.
- Inhaltsoptionen für die Textspalte: Overline, Headline, Subline, CTA-Liste.
- Das Element in der Bildspalte ist standardmäßig oben positioniert (mobil immer oben?) und kann auch mittig oder unten angeordnet werden.
3.  Styling:
- Textelemente können in 'Hell Light' für bessere Lesbarkeit auf verschiedenen Hintergründen angezeigt werden.
- Die Inhalte der ersten Spalte skalieren fluid bis zu einer maximalen Größe.

@lenadaflis @kristinrolfes wie machen wir es mit der Positionen in der Bildspalte mobil? Soll dort auch das Element an die Position, die eingestellt ist oder an eine feste Position?

Die Thematik mit dem Back Button steht auch noch im Raum:

Der optionale Back Button.
https://c4a8-web.github.io/shared-components/?path=/story/components-hero--hero-text-image-study
der ist von der Position im Moment identisch mit dem Button auf den Detailseiten. also auch eher oben ausgerichtet. wenn wir jetzt den inhalt zentrieren, beißt sich das ja mit dem zurück button. Die frage ob wir ihn überhaupt brauchen oder wie wir dort mit der Position umgehen?

**Comment by Listor** [comment]
- Back Button absolut, Padding muss mindestens die Höhe der Position haben, damit es nicht überlagert, min-height

**Comment by Listor** [comment]
Der neue Hero ist jetzt mal auf der Karriere Seite eingebunden:

https://chartreuse-sky.cloudvent.net/de/karriere

@cakageka @lenadaflis @KristinRolfes

Was meint ihr?

**Comment by KristinRolfes** [comment]
Hi @Listor, sieht gut aus! Das Scrollverhalten ist nach wie vor sehr flatterig (aber auch der alte Hero auf der Karriere Seite)

**Comment by Listor** [comment]
Meinst du das der Container sticky bleibt? Das hat Nichts mit der Komponente zu tun.

**Comment by KristinRolfes** [comment]
@Listor, ich ich weiß, ist mir nur dabei wieder aufgefallen.

**Comment by Listor** [comment]
Für die Scroll Thematik warte ich eigentlich noch darauf, dass Safari das Feature hier umsetzt:

https://caniuse.com/mdn-css_properties_scroll-timeline

Dann bekommen wir glaube ich eine sehr weiches Scroll Erlebnis hin. Hab ich noch auf dem Schirm, aber die Abdeckung ist leider auch noch im Firefox nicht gegeben.

**Comment by cakageka** [comment]
@Listor Ich gehe davon aus, dass wir überprüfen sollen, ob uns etwas auffällt, das dort nicht hingehört, richtig? Das Einzige, was mir auffällt, ist, dass die gelbe Overline jetzt weiter läuft als zuvor. Tatsächlich scheint sie mir etwas zu lang zu sein.

**Comment by Listor** [comment]
@cakageka genau und ob das generell zu den Anforderungen passt. Die Laufweite sehe ich mir an, die läuft tatsächlich weiter.

Visuell ist es leicht anders, durch die abgestimmten Anforderungen.

**Comment by Listor** [comment]
Passt jetzt. Ist auch auf der Young Professionals eingebaut:

https://chartreuse-sky.cloudvent.net/de/young-professionals

**Comment by Listor** [comment]
@KristinRolfes @lenadaflis mir ist noch eine Frage zur mobilen Shape gekommen.

![image](https://github.com/c4a8-web/shared-components/assets/4637866/442cfe95-b702-4c2c-9404-7c86e55de4a4)

Hier im Beispiel ist die Shape ja oben verortet. Wenn ich diese nun unten verorte, was passiert dann mobil?

Ist dort die Shape immer oben oder in diesem Fall unter dem Content? Oder verhält es sich ganz anders?

**Comment by KristinRolfes** [comment]
@Listor, haben wir diese Beispiel gerade irgendwo online?

**Comment by Listor** [comment]
@KristinRolfes nee die Infos habe ich aus [Figma ](https://www.figma.com/design/EOtCq50WnkBHdNZxMEDue8/GK-Website-Layouts?node-id=151-2790&t=AEsx1ciuQndg9V0R-1) gezogen.

Sitze gerade an der Positionierung und bin dabei über die Fragen gestolpert, weil ich sonst noch nicht weiß, wie ich es umsetzen sollte.

**Comment by KristinRolfes** [comment]
Ich stelle uns für Montag einen kurzen Termin ein, dann können wir die Optionen durchsprechen.

**Comment by KristinRolfes** [comment]
Doku nach Termin:

Mobil gehen wir mit kleinem Shape oben rechts um unser Corporate Design mitzunehmen. Große Bilder sind zudem zwischen Headline und Einführungstext möglich, jedoch optional. Anwendung bei z.B. Security Auge, Animationen im Karrierebereich etc.

Transitions bei Seitenwechsel in unserem Corporate Design können wir uns prinzipiell auch vorstellen, das Thema ist jedoch von einigen technischen Voraussetzungen abhängig und entsprechend nach hinten verschoben

Grobes Transition Beispiel als Reminder für später:
https://dribbble.com/shots/3467342-Palmers-Hero

**Comment by KristinRolfes** [comment]
@Listor, Lena hat eine tolle Animation für den Herobereich gebaut. #531. Wir möchten hier die Dark Variante. Kannst du das anlegen, passt das soweit auch hier mit ins Konzept? Daten findest du hier: https://c4a8.sharepoint.com/:f:/r/sites/GKGABMarketing/Shared%20Documents/General/Corp/Digital/Motion/Animation/gk-Azure-Header-Animation?csf=1&web=1&e=1h8icr

**Comment by Listor** [comment]
Ich habe jetzt die Variante mit dem Lottie, das über den ganzen Hintergrund läuft auch mit angelegt und dazu eine Test Seite in DEV angelegt, damit man es schon mal sieht.

https://chartreuse-sky.cloudvent.net/de/azure/azure-test

Von den Heros habe ich den auf der Startseite, auf den Karriereseiten/Young Professionals sowie bei den Cases den neuen Hero eingebaut.

https://chartreuse-sky.cloudvent.net/

Würde die Anderen erst Stückweise nachziehen, um zu schauen ob es Probleme in bestimmten Varianten gibt oder man etwas anpassen möchte.

Was meint ihr?

**Comment by cakageka** [comment]
Die Animation ist super. @lenadaflis + @KristinRolfes Was meint ihr?

Zu den Heros:
- Mir ist aufgefallen, dass das Bild bei den Case kleiner dargestellt wird. Möglicherweise ist dies eine bewusste Designentscheidung. Mir hat die vorherige, größere Darstellung des Bildes tatsächlich gut gefallen.

**Comment by lenadaflis** [comment]
Oh ja, die Animation kommt klasse! Gefällt mir! :-)

**Comment by Listor** [comment]
Aso das ist eine Konsequenz aus den Anforderungen. Vorher ist das Bild über den Viewport hinausgelaufen. Wenn das weiterhin gewünscht ist, passe ich das natürlich an.

**Comment by KristinRolfes** [comment]
@Listor, ja, gerne anpassen. Danke!

**Comment by Listor** [comment]
Ihr könnt die angepasste Version jetzt hier sehen:

https://chartreuse-sky.cloudvent.net/casestudies/case-dekra/

**Comment by KristinRolfes** [comment]
Danke @Listor , Seite erstrahlt wieder im alten Glanz :)

**Comment by Listor** [comment]
Der neue Hero ist jetzt auf STAGING

https://fluffy-soap.cloudvent.net/de

Auf der Startseite, Cases, Karriere

Würde vorschlagen vielleicht in den kommenden Wochen jeweils vielleicht jeweils einen Bereich der Navigation durch den neuen Hero zu ersetzen und dann schauen, ob uns Fehler auftreten.

Also Workplace dann Azure usw.

Jeweils in allen Sprachen anpassen.

- [ ] Workplace
- [ ] Azure
- [ ] Security
- [ ] Produkte
- [ ] Unternehmen
- [ ] Sonstige

Bin aber auch offen für andere Vorschläge @cakageka

**Comment by cakageka** [comment]
@Listor Das passt. Wir werden die Produkte wahrscheinlich erst ändern, wenn wir die aktualisierten Header von @lenadaflis einbauen. Die nächste Seite, die wir in Angriff nehmen, ist Azure. Sollen wir dieses Ticket offen lassen, um zu dokumentieren, welcher Header umgestellt ist?

**Comment by Listor** [comment]
Ja hätte ich gesagt, ansonsten brauchen wir dann wieder ein neues Ticket dafür. Würde es einfach hier machen.

**Comment by cakageka** [comment]
Wie können wir das Hintergrundbild verändern, um den Text lesbarer zu machen? Wäre es möglich, den Text auf eine weiße Fläche mit Transparenz zu setzen, um den Kontrast für die Schrift zu erhöhen? Andere Ideen?

![Image](https://github.com/user-attachments/assets/05c10baf-7cec-4464-b7dc-8fb82045ce91)

**Comment by Listor** [comment]
Wir können entweder eine leichte Hintergrundfläche oder einen Text "Glow" einfügen, wie auf dem alten Hero, auf den Produktseiten: 

![image](https://github.com/user-attachments/assets/64ca6e97-5243-4b08-86f4-23674921dfb5)

Auf Weiß, sieht man Beides eigentlich auch nicht. Könnte man vielleicht auch mit der Hintergrundfarbe des Heros setzen, damit es nur beim "Überlappen" wirklich auffällt.

Kann man wie bei Radius sehen, wenn man den Viewport zusammen schiebt https://www.radius-as-a-service.com/

**Comment by cakageka** [comment]
@lenadaflis Was meinst du? Ich finde das eine gute Idee für den Text. Allerdings bleibt noch der Secondary Link in der CTA-Komponente. Was haltet ihr davon, wenn wir den Secondary Link auf eine weiße Fläche setzen?

**Comment by lenadaflis** [comment]
Habs mal kurz visualisiert, dass man es sich besser vorstellen kann. Ich finde es auch total ok, wenn wir das so machen, bis der alternative Header umgesetzt ist.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/7c75c3f7-cf4f-4baa-93b8-bfbfe4142cc5">

**Comment by lenadaflis** [comment]
https://www.figma.com/design/EOtCq50WnkBHdNZxMEDue8/GK-Website-Layouts?node-id=5186-2327&t=EJMyjvO1mr3Rethd-4

**Comment by Listor** [comment]
Der letzte Stand ist jetzt auf DEV

https://chartreuse-sky.cloudvent.net/de/azure/azure-test/

Den Parameter "textShadow" hatte ich vorher auch schon eingebaut, nur dort war es nur weiß und in der Headline anders als in der subline. 

CTA habe ich auch angepasst mit einem extra Parameter.

**Comment by cakageka** [comment]
Funktioniert gut. Kann meines Erachtens ins Staging.

**Comment by Listor** [comment]
Auf STAGING https://fluffy-soap.cloudvent.net/de/azure/azure-test/

**Comment by cakageka** [comment]
Auf der AzERE Seite eingebaut. Weiß funktioniert nicht - da man hier wahrscheinlich keinen Shadow setzen kann - daher als Hintergrundfarbe bgColor: "var(--color-black-2)" gewählt
