### ISSUE TITLE
Favicons in Bing // anderen Suchmaschinen

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#156]
Das Favicon sollte in allen Suchmaschinen korrekt angezeigt werden. Unter Bing wird z.B. kein Favicon angezeigt.

Als positiv Beispiel das funktioniert kann man sich LinkedIn anschauen.

**Comment by Listor** [comment]
So ich habe STAGING von Scepman mal geupdated. Dabei habe ich auch das apple-touch-icon in das von scepman geändert und die Größe von 256 auf 180 reduziert. Das ist laut der offiziellen Apple Seite das größte Format.

Im Header wird jetzt nur auf das "favicon.ico" verwiesen.

Zum Testen habe ich https://realfavicongenerator.net/ benutzt. Dort wird dir auch angezeigt, ob das favicon.ico alle Formate hat. Notwendig wäre dort aktuell nur:

16x16
24x24
32x32
48x48

Zusätzlich liegt dort noch 64x64 und 128x128 drin. Um so mehr Formate man darin speichert, um so größer wird auch die Datei.

Dort hat vorher schon eine Datei gelegen, die die selben Formate nur in umgekehrter Reihenfolge gespeichert hat. Ich vermute diese wäre auch okay. Ich habe diese Datei jetzt mit einem Konsolen Tool zusammen gesteckt, geht aber wohl auch mit GIMP. Mit Photoshop habe ich kein Plugin gefunden, dass es aktuell kann und kostenlos ist.

Auf STAGING sind noch Änderungen, von denen ich nicht weiß, ob sie live gehen sollen oder nicht.

Wenn es auf PROD ist, einmal die url über Google + Bing crawlen lassen und dann heißt es abwarten. Bei uns hat es noch 1 Woche gedauert, damit die Änderungen vom Favicon Crawler geupdated wurden. Ist vielleicht bei einer Seite mit mehr Traffic anders.

Google:  https://search.google.com/search-console
Bing: https://www.bing.com/webmasters/home

**Comment by cakageka** [comment]
Danke dir!

**Comment by cakageka** [comment]
Hängt mit [#251](https://github.com/c4a8-web/marketing/issues/251) zusammen

**Comment by Listor** [comment]
Bei uns hat das Favicon in Google geklappt. Auf Bing sind wir immer noch leer. Habe einige Posts dazu gefunden, die sagen, dass der Support ihnen helfen konnte. https://www.bing.com/webmasters/help/webmasters-support-24ab5ebf

Das habe ich jetzt bei uns mal probiert, aber noch kein Ergebnis. Sollten wir vielleicht machen, sofern wir in Google bei allen Produkten, das gewünschte Ergebnis haben. Dann muss man es vielleicht nur 1x anstoßen bei Bing.

Auf Duckduckgo wurde unser Favicon jetzt auch angezeigt.

**Comment by Listor** [comment]
Tatsächlich wird unser Favicon jetzt auf Bing.com angezeigt. Finde es zwar weird diesen Prozess gehen zu müssen, aber das scheint wohl der einzig funktionierende Weg im Moment zu sein.

**Comment by cakageka** [comment]
Könntest du das hier auch gleich mit umsetzen, wenn du dich um https://github.com/c4a8-web/marketing/issues/668 kümmerst? Danke.

**Comment by eugenie-gkgab** [comment]
Habe ich alles soweit umgesetzt und sowohl bei Bing als auch in der Search Console zur Indexierung angestoßen. Bei Bing habe ich das ganze über den Support geregelt, wie beschrieben. Jetzt heißt es abwarten, ob es klappt.

**Comment by cakageka** [comment]
Yeah, SCEPman Fav auf Bing geändert:

![Image](https://github.com/c4a8-web/shared-components/assets/1835330/755eb78f-4b7c-4c2e-928c-3ddf52949f45)

**Comment by eugenie-gkgab** [comment]
Favicons werden jetzt überall korrekt angezeigt. :)
