### ISSUE TITLE
Change background slides of the "Conditional Access Intro" presentation

### ISSUE THREAD

**Issue by jay-7ee** [c4a8-web/shared-components#163]
Could you please update the background of the slide of this presentation with the current slides (company name still includes gab)?

https://c4a8.sharepoint.com/:p:/r/sites/GKGABSlides/_layouts/15/Doc.aspx?sourcedoc=%7B7F805B0E-0E1B-41A6-BBD9-A96F1CD1C787%7D&file=202204-identity-conditional-access.pptx&action=edit&mobileredirect=true

**Comment by lenadaflis** [comment]
Logos and URLs have been updated. Please check again briefly.

**Comment by jay-7ee** [comment]
Thank you very much. Will close the issue.
