### ISSUE TITLE
Azure Übersichtsseite

### ISSUE THREAD

**Issue by KristinRolfes** [c4a8-web/shared-components#183]
Folgende Module müssten für die Übersichtsseite neu erstellt, bzw. abgeändert werden. Gerne Ticket bei Bedarf aufteilen:

https://www.figma.com/design/EOtCq50WnkBHdNZxMEDue8/GK-Website-Layouts?node-id=1177-7828&t=McCjKkoVAO4RtlTh-1

- [x] - Überlappendes Logomodul welches wir zukünftig zwischen Hero und Content setzen können
- [x] - Szenariosmodul (können wir da bei auf Bestehendes zurückgreifen?)
- [x] - Einführungsmodul. Links Headline, rechts tiefergehende Infos. Gerne vom Scrollverhalten wie hier im Beispiel aufbauen: https://www.dteckt.com/
- [x] - "Unsere Services" sollten halbwegs mit unserem Tab Modul aus dem Karriere Bereich abgedeckt sein
- [ ] Einbindung Floating Action Kontakt Button + Transition zum Kontaktbereich beim scrolling
- [ ] Cases Modul neu überarbeiten

**Comment by lenadaflis** [comment]
https://c4a8.sharepoint.com/:f:/r/sites/GKGABMarketing/Shared%20Documents/General/Corp/Digital/Motion/Animation/gk-Azure-Header-Animation?csf=1&web=1&e=1h8icr

**Comment by Listor** [comment]
Hero kommt dann über das andere Ticket https://github.com/c4a8-web/shared-components/issues/154 und ist dort bereits umgesetzt.

**Comment by Listor** [comment]
Aktueller Stand ist hier zu sehen auf DEV https://chartreuse-sky.cloudvent.net/de/azure/azure-test/

Die Komponente unter "Wo stehen Sie im Moment?" ist noch in Bearbeitung und funktioniert noch nicht richtig.

Man kann die Logo-Liste im Hero sehen, wie sie leicht durchscrollt, auf kleineren Viewports. Was denkt ihr @lenadaflis @KristinRolfes

**Comment by KristinRolfes** [comment]
@Listor, finde ich gut! Ich dachte ursprünglich das könnte zu viel werden, funktioniert jedoch in so langsam.

**Comment by lenadaflis** [comment]
Ich finds auch gut! Das einzige, was mir noch auffällt: Wenn es bei den kleineren Viewports in die Scroll-Variante wechselt, haben die Logos recht wenig Abstand zueinander (momentan 1rem, wenn ich das richtig sehe). Was meint ihr, sollten wir den noch etwas erhöhen? Vielleicht auf 2rem?

**Comment by Listor** [comment]
Ja stimmt den Abstand passe ich an.

**Comment by Listor** [comment]
Habe den neusten Stand auf DEV gespielt und den Platzhalter Content schon großenteils eingebaut.

Bin noch an der Komponente mit den Step 1 - Step 4 dran, damit diese so aussieht wie in Figma:

https://chartreuse-sky.cloudvent.net/de/azure/azure-test/

**Comment by Listor** [comment]
So ich habe die Step 1 - Step 4 Komponente jetzt fertig und auf DEV deployed.

Wenn das für euch so passt @lenadaflis @cakageka dann würde ich das dann auf STAGING spielen, damit du Caro, es heute dann deployen kannst.

DEV: https://chartreuse-sky.cloudvent.net/de/azure/azure-test/

**Comment by cakageka** [comment]
Passt für uns!

**Comment by lenadaflis** [comment]
Ah, das einzige, was mir gerade noch auffällt – denkst du, wir könnten eine kleine Transition ergänzen? Hab sie hier mal unten reingepfuscht :-)

<img width="395" alt="image" src="https://github.com/user-attachments/assets/344b2612-bcc8-48b9-8521-f897dff737cc">

**Comment by Listor** [comment]
Ist auf STAGING mit der gewünschten Transition 

https://fluffy-soap.cloudvent.net/de/azure/azure-test/

Wollen wir das Ticket für den Floating Action Button und das Case Modul weiterverwenden oder für die beiden Aufgaben eigene Tickets machen @cakageka ?

Würde Letzteres bevorzugen :D

**Comment by cakageka** [comment]
Für Cases und Floating Action Button gibt es zwei neue Issues.
