### ISSUE TITLE
Canonical Tags

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#186]
In der Google Search Console, sollte ich mir ja die Infos zu den Canonical Tags anschauen.

Nachdem ich mir das jetzt angeschaut habe, konnte ich feststellen, dass die Ausgabe korrekt ist und keinen Fehler aufweist.
Im Falle von Scepman sagt Google im Grunde genommen nur, wir indizieren die Seite www.scepman.com/start-now nicht, weil es bereits
eine indizierte Seite gibt und das canonical Tag auf diese Seite zeigt. Mit der URL www.scepman.com/start-now/.

Also im canonical tag hängen wir schon den / an. Google weist uns hier nur darauf hin. Ist also meines Erachtens nach auch kein Problem, sondern nur eine Info.

Die anderen URLs z.B. bei Scepman die nicht als kanonisch festgelegt wurden, kommen aus den Docs wie z.B. https://docs.scepman.com/other/faqs/~/comments und dort kann ich keine Anpassungen vornehmen.

Auf GK sind es Dokumente wie https://www.glueckkanja.com/documents/onepager/gkgab-AzureAwarenessOnePager.pdf dort müsste im Header ein Canonical Link gesetzt werden auf Url's mit einem Hash. Dort kann ich jedoch auch keine Anpassungen vornehmen.

**Comment by cakageka** [comment]
Danke @Listor
