### ISSUE TITLE
Accordion: Mehr Abstand zwischen HL und Subline

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#207]
https://github.com/c4a8-web/shared-components/blob/d39aa5ab02e16912f6b792f8b6b9c1fde817c71b/assets/js/vue/accordion.js#L172

s. #904

**Comment by Listor** [comment]
Ist auf STAGING deployed https://fluffy-soap.cloudvent.net/de/azure/azure-emergency-response-environment/

**Comment by cakageka** [comment]
Danke.
