### ISSUE TITLE
New Snippet: Formular Wizard

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#231]
![Image](https://github.com/user-attachments/assets/2fccb96d-319d-45b9-8cde-d68f3c0a77f6)

**Copy**

glueckkanja Workaholic-Test: 
Finden Sie jetzt heraus, wie hoch Ihr IT-Frust-Level ist!

(Info)
Achtung: Punkte hinter den Antworten nur für die interne Punkterechnung.

(Frage 1)
Ein Kollege sendet eine Mail und bittet Sie darin um einen UK-Adapter für sein HDMI Kabel, das er für eine wichtige Präsentation in London benötigt. Wie reagieren Sie?

- Ich gehe nach Hause. (5 Punkte)
- Ich springe aus dem Fenster. (10 Punkte)
- Ich schreibe eine 2seitige Replik, in der ich dem Kollegen in aller Ausführlichkeit erkläre, dass ein UK-Adapter ausschließlich für die Stromversorgung seines Laptops von Nöten ist. (0 Punkte)

(Frage 2)
Eine Kollegin ruft Sie ganz aufgeregt aus dem Homeoffice an und brüllt ins Telefon, dass ihr Bildschirm schwarz ist. Was tun Sie?

- Ich brülle zurück – allerdings Schimpfwörter. (5 Punkte)
- Ich stelle mir vor, dass die Kollegin mit verbundenen Augen über eine 8 spurige Autobahn spaziert und erfreue mich am Ergebnis dieses Gedankenspiels. (10 Punkte)
- Ich erkläre der Kollegin – wie schon viele Male zuvor –, dass ihr Bildschirm Energie in Form von Strom benötigt und bitte sie deshalb, diesen ebenfalls einzuschalten. (0 Punkte)

(Frage 3)
Die Marketingreferentin hat einen wichtigen Videocall mit der Werbeagentur. Wenige Minuten vorher meldet sie sich bei Ihnen, weil ihr Headset mal wieder nicht richtig funktioniert. Was tun sie?

- Ich lasse alles stehen und liegen, eile zu ihr und erkläre ihr erneut die Funktionen der kleinen Knöpfchen am rechten Ohrhörer. (0 Punkte)
- Ich übernehme den Videocall mit der Werbeagentur, schieße die vorgestellte Werbekampagne direkt ab und bitte darum, eine neue mit richtig vielen bösen Kraftausdrücken zu entwickeln. (10 Punkte)
- Ich trinke erstmal in Ruhe einen Espresso (oder zwei, oder drei). Anschließend platze ich in den Call, fummle mehrere Minuten umständlich am Headset der Kollegin herum, wobei ich versehentlich (in Anführungszeichen!) an die Off-Taste ihres Laptops stoße. (5 Punkte)

(Frage 4)
Der Kollege aus dem dritten Stock hat mal wieder sein Passwort vergessen. Wie reagieren Sie?

- Ich tätowiere es ihm auf seinen Arm – mit Tackerklammern. (10 Punkte)
- Ich atme dreimal tief ein und aus. Anschließend denke ich mir 5 neue Schimpfwörter für ihn aus, die ich wie immer fein säuberlich in das bereits gut gefüllte Büchlein auf meinem Schreibtisch eintrage. (5 Punkte)
- Ich vergebe ein neues Passwort für den Kollegen und bitte ihn, es sich diesmal gut zu merken. (0 Punkte)

(Frage 5)
Ein Kollege kommt freudestrahlend in ihr Büro und berichtet Ihnen von einer überraschenden Millionen-Erbschaft eines afrikanischen Onkels, von der er gerade via Email erfahren und sich sogleich über den hinterlegten Link zurück gemeldet hat. Was machen Sie?

- Sie setzen sofort alle Security-Hebel in Bewegung und erklären dem Kollegen, dass es sich bei der Erbschaft vermutlich um einen Angriff böser Hacker handelt. Anschließend nehmen Sie ihn in den Arm und trösten ihn über den entgangenen Millionen hinweg. (0 Punkte)
- Sie holen eine gute Pulle Schampus und stoßen mit dem Kollegen auf die viele Kohle an. (10 Punkte)
- Sie vermitteln den Kollegen an Ihren Bankberater weiter, damit dieser das Geld sinnvoll anlegen kann. (5 Punkte)

(H2-1)
Testauswertung:
So hoch ist Ihr IT-Frust-Level!

(Zahlenfeld: Addition der einzelnen Punkte pro Aufgabe ausgedrückt in Prozent)
00 Prozent

(Copy Auswertung 0 – 20 Prozent)
Sie sind beherrscht und reagieren auch in stressigen Situation meistens besonnen. Damit das auch zukünftig so bleibt, empfehlen wir Ihnen, unsere Therapieübungen als Prävention in Ihren Arbeitsalltag einzubauen. 

(Copy Auswertung 30 – 70 Prozent)
Manchmal würden Sie gerne aus Ihrer Haut fahren, können sich dann aber meisten gerade noch so beherrschen. Unser Tipp: Nutzen Sie in besonders stressigen Momenten unsere „Cool-Down-Art Übung“ und lassen Sie damit alle Ihre negativen Emotionen raus.

(Copy Auswertung 80 – 100 Prozent)
Oh, wow – Sie stehen kurz vor der finalen Explosion! Leider können selbst unsere wissenschaftlich erprobten Selbsthilfeübungen bei Ihnen keine Abhilfe mehr schaffen. Bitte wenden Sie sich an einen unserer Fachberater, damit dieser möglichst kurzfristig für Sie individuelle Lösungen in Ihren Problemfeldern erarbeiten kann.

**Comment by Listor** [comment]
@cakageka ich nehme an bei der Auswertung meintest du von 0-30, weil die nächste Auswertung ab 30 anfängt und bei 30-70 auch 30-80 oder?

**Comment by Listor** [comment]
Ich habe den aktuellen Stand der Survey mal auf DEV gespielt. Also der Branch feature/it-workaholics wird gerade auf DEV angezeigt und kann dort auch getestet werden.

Ich habe auf der Ergebnisseite den errechneten Score in % eingeblendet, damit man besser testen kann. 

Jetzt fehlt nur noch die Progressleiste, ansonsten würde ich denken, dass die Komponente funktioniert und fertig ist.

Zu Testen: https://chartreuse-sky.cloudvent.net/de/it-workaholics/

**Comment by cakageka** [comment]
@Listor Ja, das stimmt. 0-30, 30-70, 70-100. Sorry.

**Comment by Listor** [comment]
Habe jetzt die Progress Leiste eingebaut und die Abstände Mobil angepasst. Dort passen wir die Höhe dem aktuellen Element an, weil wir stark unterschiedlich hohe Elemente haben. Auf Desktop nehmen wir die Höhe vom höchsten Element.

Wenn es vom Testing her passt, würde ich die currentScore als Debug Wert aus der Ergebnisseite nehmen.

**Comment by cakageka** [comment]
Sieht schon super aus @Listor. Folgende Anmerkungen:
- Wir müssen davon ausgehen, dass die meisten Nutzer das mobil ansehen. Wenn man von Frage zu Frage springt, wäre es hilfreich, wenn immer „Frage X von Y“ sichtbar bleibt, damit die Orientierung erhalten bleibt.
<img src="https://github.com/user-attachments/assets/a25df5b7-d0ee-4d37-a5ae-f04fa8237d8e" width="300">
<img src="https://github.com/user-attachments/assets/89298aac-5021-4016-bdc3-97a64923c62d" width="300">

- Die Abstände sind noch etwas groß (HL, Subline, Zeilenabstand Subline)

<img src="https://github.com/user-attachments/assets/6fa6cfba-9475-4cc1-864e-909630833884" width="300">

cc @KristinRolfes

**Comment by Listor** [comment]
@cakageka wenn wir wollen, dass die Frage immer sichtbar bleibt könnten wir schauen, ob wir das Element gut Sticky bekommen, was dann mit einer Schattenkante nach unten die Fragen überlappt oder wir müssen nach Oben springen. Die Inhalte sind teilweise sehr lang und deshalb passen sie nicht komplett auf einen viewport.

**Comment by cakageka** [comment]
cc @KristinRolfes 

@Listor Finde ich gut.

**Comment by Listor** [comment]
Hab ich vorsorglich schon auf DEV geworfen, könnte man aber auch leicht wieder entfernen.

**Comment by cakageka** [comment]
@Listor Das fühlt sich beim Scrollen richtig gut an. Danke.

**Comment by Listor** [comment]
Ist ja auch bereits auf PROD und umgesetzt, deshalb würde ich hier auch das Ticket schließen.
