### ISSUE TITLE
New Snippet: Video Slider

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#232]
![Image](https://github.com/user-attachments/assets/9dbe0e77-7a46-4122-be5d-e3785584c6da)

**Elemente**
- HL
- Subline
- Tabs als Sprungmarke zu Video
- Video öffnen sich in der Lightbox
- Videos erhalten Captions
- Zentraler CTA

**Comment by Listor** [comment]
@cakageka meinst du mit Zentraler CTA, dass die Videos alle auf die selbe Seite verlinken oder was meinst du mit zentral?

**Comment by cakageka** [comment]
Der CTA sollte als Sprungmarke direkt zum Test führen, nicht zu den Videos. Diese öffnen sich ja in der Lightbox.

**Comment by Listor** [comment]
Achso das "Teste dein Stresslevel" gehört nicht mehr zu dem Video, sondern ist der zentrale CTA, der runterscrollt zur sprungmarke?

**Comment by cakageka** [comment]
Genau

**Comment by cakageka** [comment]
Die Video werden mit Captions angezeigt. Direkt darunter befindet sich dann die Sprungmarke, die zum Test führt.

**Comment by Listor** [comment]
Liegen die Videos eigentlich auf Youtube oder werden sie selbstgehostet? Wenn Letzteres, in welchem Format liegen die Videos vor?

**Comment by Listor** [comment]
Ich habe eine Version der Komponente auch auf DEV eingebunden:

https://chartreuse-sky.cloudvent.net/de/it-workaholics/ 

Dort müsste dann nur noch der Inhalt durch den realen Content ausgetauscht werden.

**Comment by Listor** [comment]
Die Tabs passen mobil nicht wirklich in den Viewport, weshalb ich sie provisorisch swipebar gemacht habe.

**Comment by cakageka** [comment]
Das passt super.

**Comment by Listor** [comment]
Denke wir sind hiermit ja bereits durch, deshalb schließe ich das Ticket.
