### ISSUE TITLE
Styling-Option für Content-Scroller hinzufügen

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#233]
![Image](https://github.com/user-attachments/assets/e9759abc-bb3c-4d05-98e8-6b83bd565d5b)

**Comment by Listor** [comment]
Eine Version ist jetzt auf DEV https://chartreuse-sky.cloudvent.net/de/it-workaholics/

**Comment by Listor** [comment]
Würde ich als erledigt ansehen
