### ISSUE TITLE
New Snippet: Game

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#234]
![Image](https://github.com/user-attachments/assets/7e6ff8e3-cf0d-4734-a335-027588adf6e5)

Whack a mole
https://codepen.io/themrsami/pen/EaYaZNO

**Comment by Listor** [comment]
Das Spiel ist jetzt auf DEV https://chartreuse-sky.cloudvent.net/de/it-workaholics/

![Image](https://github.com/user-attachments/assets/61fb84f6-3abc-4fd0-b947-01c8face4778)

Mobil denke ich, dass es ein Problem werden könnte, wenn wir 2x3 anzeigen. Dadurch wird der Inhalt sehr hoch und es könnte bei nicht so hohen Geräten dazu führen, dass man die Score und das Spielfeld nicht gleichzeitig sieht.

Habe es mal auf 3x2 gestellt. Denkbar wären auch 2x2 oder sogar 3x3 könnte ich mir noch vorstellen. Die Elemente sind immer noch gut klickbar nach meinem  Empfinden.

Diesen Wert kann man sehr leicht verändern.

Ansonsten habe ich denke ich alle Anforderungen umgesetzt. Die Spieltexte wie "Spiel starten" usw. sind bereits für DE, EN, ES eingepflegt. Bei ES kein Gewehr :D 

Mir ist beim Spielen noch aufgefallen, dass irgendwie ein Feedback fehlt, wenn man den Maulwurf trifft. Fühlt sich dadurch noch nicht so spaßig an.

**Comment by Listor** [comment]
![Image](https://github.com/user-attachments/assets/9d6a77b2-f7da-4c6e-95c6-817165ec911e)

**Comment by Listor** [comment]
Das hatte ich tatsächlich im Original übersehen und nicht wahrgenommen. Wäre für etwas visuell stärkeres. Kann aber auch das Konfetti ähnlich im Original umsetzen @cakageka

**Comment by cakageka** [comment]
@KristinRolfes Deine Meinung?

**Comment by KristinRolfes** [comment]
Ich finde Konfetti super!

**Comment by cakageka** [comment]
Folgende Änderungen bitte:
- Wenn man auf den Kopf haut, soll Konfetti erscheinen
- Sobald das Spiel gestartet ist, bitte automatisch stoppen, wenn der Nutzer hoch- oder runterscrollt. Andernfalls erscheint die Meldung „Spiel Ende“ als Overlay über einem anderen Snippet (siehe Screenshot).
<img width="1142" alt="Image" src="https://github.com/user-attachments/assets/7bce292d-0576-4c1d-8eca-931b3cbecd06" />
- Das Overlay sollte sich automatisch schließen, sobald gescrollt wird, um zu verhindern, dass es sich über andere Widgets schiebt

**Comment by Listor** [comment]
- Es erscheint jetzt Konfetti bei einem Treffer
- Das Overlay kann die Komponente nicht verlassen, es bleibt nur über der Komponente und ist auch nur dort sichtbar. 
- Ich habe trotzdem eingebaut, dass wenn das Overlay offen ist und man scrollt es sich schließt. Den Fall beim Spielen halte ich für gefährlich, weil man mobil auch schnell mal scrollt beim Spielen und dann wieder von Vorne anfangen müsste. Das ist denke ich eher frustrierend und sollten wir vermeiden.

Die Anpassungen sind auf STAGING https://fluffy-soap.cloudvent.net/de/it-workaholics/
