### ISSUE TITLE
Soll .video-slider wirklich min-height: 100vh nutzen?

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#235]
Aktuell sorgt die CSS-Regel dafür, dass die .video-slider-Komponente die gesamte Höhe des Viewports einnimmt:

https://github.com/c4a8-web/shared-components/blob/5719540a65a28a874e408d54e89e27d99355a04f/assets/scss/components/_video-slider.scss#L9

Das führt bei kleineren Inhalten zu zusätzlichen leeren Flächen und Abständen nach unten.

Muss das Modul immer die gesamte Viewport-Höhe einnehmen?
Was spricht dafür, was dagegen?

Wenn nichts dagegen spricht, würde ich gerne darauf verzichten.

**Comment by Listor** [comment]
Dafür spricht aus meiner Sicht eher das Layout. Kann es aber auch anpassen.

**Comment by Listor** [comment]
Ist jetzt auf STAGING https://fluffy-soap.cloudvent.net/de/it-workaholics/

**Comment by cakageka** [comment]
Super. Danke. Wir haben vorhin gemeinsam entschieden, dass wir hier nicht auf Fullsize gehen wollen.
