### ISSUE TITLE
Content Scroller: Styling Änderung

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#238]
https://github.com/c4a8-web/shared-components/blob/1f0946b0ebab1ff19b23bf200a4ff466d7337238/assets/scss/components/_content-scroller.scss#L1

Können wir mobil diese Linie entfernen?

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/777f2b39-4de7-46e4-9e0f-24fa8836b139" />

**Comment by cakageka** [comment]
Tatsächlich sollten wir mobil den Pro Tipp entfernen

<img width="534" alt="Image" src="https://github.com/user-attachments/assets/71990bdf-c410-4031-8545-35b6c1ed6c70" />

**Comment by Listor** [comment]
Ist mobil angepasst, also Linie raus und Pro-Tipp ausgeblendet:

https://fluffy-soap.cloudvent.net/de/it-workaholics/

**Comment by cakageka** [comment]
Super. Danke Listor
