### ISSUE TITLE
Änderung der Adblock Pop Size bitte auf alle Produktseiten übertragen

### ISSUE THREAD

**Issue by cakageka** [c4a8-web/shared-components#89]
Bitte die Änderung in Bezug auf die Größe und Zeitpunkt der Anzeige des Adblock Popups auf alle Produktseiten übertragen (s. Commit https://github.com/c4a8-web/shared-components/commit/199249395f806007ffb47be12d684bb7956eeff7)

**Comment by cakageka** [comment]
Ich habe festgestellt, dass die Änderungen bereits auf einigen unserer Produktseiten umgesetzt wurden, bspw. auf radius-as-a-service.com. Allerdings steht die Implementierung auf der KONNEKT-Seite noch aus. Zudem ist mir auf der SCEPman-Seite etwas aufgefallen: Selbst wenn ich den Wert '@gab_adBlockInfo' im LocalStorage lösche, wird mir kein Adblocker angezeigt.

![Image](https://github.com/c4a8-web/shared-components/assets/1835330/8412b22c-eb8e-4ff9-9bea-189121d2e3a0)

**Comment by Listor** [comment]
Die werden immer mit den Deployments automatisch ausgerollt. Konnte das auf SCEPman jetzt nicht nachvollziehen. Bei mir kam im Chrome und im Edge, den du scheinbar benutzt, immer das Popup. Hast du im Edge auch uBlock installiert?

Ich habe die anderen Systeme deployed. Auf SCEPman habe ich aber noch nicht auf PROD deployed, weil du noch Änderungen drin hattest, die noch nicht live gehen sollten?

- Radius ([PROD](https://www.radius-as-a-service.com/)) 
- Unified ([PROD](https://www.unified-contacts.com/)) 
- SCEPman ([STAGING](https://voiceless-panther.cloudvent.net/)) 
- RealMigrator ([PROD](https://www.realmigrator.com/))
- RealmJoin ([PROD](https://www.realmjoin.com/))
- Konnekt ([PROD](https://www.konnekt.io/))
