### ISSUE TITLE
Smilie Animation auf der Karriere Seite defekt

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#90]
Auf der Karriere Seite unter iPhone Safari, ist die Smilie Animation kaputt, bzw. überlagert sich.

System:

https://chartreuse-sky.cloudvent.net/de/karriere (DEVELOP)

**Comment by Listor** [comment]
Kann den Feature-Branch irgendwie nicht verlinken. https://github.com/c4a8-web/shared-components/tree/fix/hero-animation

**Comment by cakageka** [comment]
Animation funktioniert jetzt auf DEV. Bitte ins STAGING übernehmen.
