### ISSUE TITLE
Berufseinsteigerseite auf Englisch übersetzen

### ISSUE THREAD

**Issue by Listor** [c4a8-web/shared-components#95]
Die neue Berufseinsteigerseite soll auch als Englische Seite angelegt werden.

https://fluffy-soap.cloudvent.net/de/berufseinsteiger

**Comment by JHPNE** [comment]
Die Englische Seite ist hier erreichbar: https://fluffy-soap.cloudvent.net/en/young-professionals

**Comment by Listor** [comment]
@JHPNE kannst du gerne Caro zuweisen zum review

**Comment by cakageka** [comment]
@JHPNE Du hast vergessen den "lang:en" Parameter einzufügen, daher funktioniert der Switch nicht. Ich habe es gerade nachgetragen.
